### ISSUE TITLE
upload_max_filesize in php.ini not working

### ISSUE THREAD

**Issue by elvisron** [coloso/symfony-docker#10]
By default uploads exceeding 1M throws an error. The logical thing to do next is to navigate to docker/php/php.ini and add a line of code: upload_max_size = .... How can this issue be resolved?

**Comment by coloso** [comment]
Do you mean: `upload_max_filesize = 48M` ?
After changing the php.ini you have to rebuild your container.

**Comment by elvisron** [comment]
My bad. Exactly `upload_max_filesize = 250M`. After changing I restarted the container. Shouldn't that work? I did a `docker-compose up --build` still doesn't work.

**Comment by coloso** [comment]
whats in your error.log?
