### ISSUE TITLE
Symfony migrations don't work; could not find driver

### ISSUE THREAD

**Issue by wluberti** [coloso/symfony-docker#11]
First of all: Thank you for this repo. I've wanted to try fiddling around with Symfony and Docker for some time now and thought the release of version 5 was a good moment to do it. However when following one of the Symfony 5 tutorials (https://symfony.com/doc/current/security.html) I get stuck with the `php bin/console make:migration` command:

```
In AbstractMySQLDriver.php line 106:
  An exception occurred in driver: could not find driver  

In PDOConnection.php line 31:
  could not find driver  

In PDOConnection.php line 27:
  could not find driver
```

Curiously enough if I try entering a page that uses the database connection (http://localhost:8080/login see https://gitlab.com/wluberti/mixup for full repo) I get a different error:
```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["email@address.whatever"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symfony.user' doesn't exist
```
(which is logical, because I can't run the migration to create the table). But it can make a connection! If I mistype the password in the DATABASE_URL string in my .env the error changes to  : `An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.28.0.3' (using password: YES)` again pointing to a working driver.

Any idea what I need to fix to get the `php bin/console make:migration` command to work and/or  what else I am doing wrong?

**Comment by coloso** [comment]
Hey wluberti,
i guess there is no User table in your database. Do you executed bin/console doctrine:schema:create ?

**Comment by wluberti** [comment]
If I run `php bin/console doctrine:schema:create` I get a similar error that the driver could not be found:
```
 !                                                                                                                      
 ! [CAUTION] This operation should not be executed in a production environment!                                         
 !                                                                                                                      

 Creating database schema...

In ToolsException.php line 34:
  Schema-Tool failed with Error 'An exception occurred in driver: could not find driver' while executing DDL: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB                                                                                                                                                                                     
                                                                                                                                                                                             
In AbstractMySQLDriver.php line 106:
  An exception occurred in driver: could not find driver  

In PDOConnection.php line 31:
  could not find driver  

In PDOConnection.php line 27:
  could not find driver 
```

**Comment by coloso** [comment]
Strange. I checked out your mixup repo and everything worked fine for me.
Maybe you have some issus in your container. Try to rebuild:
1. docker-compose down
2. docker system prune (cleans everything)
3. docker-compose up --build
after that check php bin/console doctrine:schema

**Comment by wluberti** [comment]
I've followed your steps (even with `docker system prune -a --volumes` just te be sure) and with just `php bin/console doctrine:schema` I get "Command "doctrine:schema" is not defined.". If I try `php bin/console doctrine:schema:create` I get the same error as described in my previous comment

**Comment by coloso** [comment]
maybe its an little bit stupid question: are you connected to the container when the command are executed?

**Comment by wluberti** [comment]
pffff. not a stupid question at all :-( That was exactly the problem. After connecting with `docker-compose exec php sh` and then running the console commands everything worked as it should. Thanks you so much for your time and pointing this out to me! Grtz Wouter

**Comment by OthmaneAlaoua** [comment]
Hello, 

Try to install the driver on your machine (not docker).
