### ISSUE TITLE
Permission denied in sh docker

### ISSUE THREAD

**Issue by lukasmat** [coloso/symfony-docker#13]
Hello,

when I connected in docker sh (command docker-compose exec php sh) I have Permission denied error (in var/www/symfony folder: composer create-project symfony/website-skeleton .).
    
error:
[UnexpectedValueException]                                                                       
  RecursiveDirectoryIterator::__construct(/var/www/symfony/.): failed to open dir: Permission denied 

How change permissions in symfony folder?

**Comment by coloso** [comment]
Hi,
i cannot reproduce. Tested on Mac and Ubuntu:
```  
...
- Configuring symfony/maker-bundle (>=1.0): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.
```
Which OS are u using?

**Comment by lukasmat** [comment]
I'm using Fedora 32.

**Comment by coloso** [comment]
Do you closing the terminal after `docker-compose up --build`?

**Comment by lukasmat** [comment]
Yes :)

**Comment by coloso** [comment]
No, that can't work. Im wondering how you can connect to the container... anyway: Please let the terminal open and open a another one, which you connect and execute your Symfony install command.

That should do the trick!

**Comment by lukasmat** [comment]
[Screencast from 08-06-2020 11:01:32 AM.zip](https://github.com/coloso/symfony-docker/files/5033832/Screencast.from.08-06-2020.11.01.32.AM.zip)

**Comment by lukasmat** [comment]
Yes, Docker works with ubuntu. :)

Thanks for your help.
