### ISSUE TITLE
Composer fails

### ISSUE THREAD

**Issue by gruz** [coloso/symfony-docker#2]
$ docker-compose exec php bash

root@aad8ae65b5da:/var/www/html# composer create-project symfony/website-skeleton symfony
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing symfony/website-skeleton (v4.2.1.5)
    Failed to download symfony/website-skeleton from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
    Now trying to download from source
  - Installing symfony/website-skeleton (v4.2.1.5): Cloning 8f9d15482b from cache
Created project in symfony
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for facebook/webdriver 1.6.0 -> satisfiable by facebook/webdriver[1.6.0].
    - facebook/webdriver 1.6.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  Problem 2
    - facebook/webdriver 1.6.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - symfony/panther v0.2.0 requires facebook/webdriver ^1.5 -> satisfiable by facebook/webdriver[1.6.0].
    - Installation request for symfony/panther v0.2.0 -> satisfiable by symfony/panther[v0.2.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
root@aad8ae65b5da:/var/www/html# composer create-project symfony/website-skeleton symfony

**Comment by coloso** [comment]
Hello Gruz,
thank you for hinting this issue. I fixed this missing extension and now it should be work again.
