### ISSUE TITLE
Error: Cannot start service db: network not found

### ISSUE THREAD

**Issue by ser-gent** [coloso/symfony-docker#3]
Hi !
`$ docker-compose up -d`
it get error message as following : 
Starting symfony-docker_php_1 ... 
Starting symfony-docker_web_1 ... 
Starting symfony-docker_db_1  ... error

ERROR: for db  Cannot start service db: network 949d928a3a5828677117fdea0f8dd6aa068ac9fb52a648c738d85286d8e488a0 not found
ERROR: Encountered errors while bringing up the project.

But I don't understand why my network wasn't not found.

When I run `$ docker network ls`
The result was :
NETWORK ID          NAME                DRIVER              SCOPE
45e11d2c6fd7        bridge              bridge              local
abecd6b6abbb        host                host                local
1ee3598fde99        none                null                local

Any suggestion?

**Comment by coloso** [comment]
Hi, try to reset your docker `docker system prune` and delete all images `docker rmi $(docker images -a -q)` and remove all containers `docker rm $(docker ps -a -q)`.

At least:  `docker-compose build` after cleanup should do the magic!

**Comment by coloso** [comment]
please clone repo again, containers are using alpine now.
